imageCredentials:
  create: false
  name: csp-registry-secret # When create is false please specify
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""

enforcerToken: ""

enforcerTokenSecretName: null
enforcerTokenSecretKey: null
enforcerLogicalName: 

privileged: true

hostRunPath: "/var/run" # pks - /var/vcap/sys/run/docker
runcInterception: true 
sendingHostImagesDisables: false

rbac:
  enabled: false
  roleRef:

gate:
  host: csp-gateway-svc # example
  port: 8443

image:
  repository: enforcer
  tag: "4.6"
  pullPolicy: IfNotPresent

livenessProbe: {}
readinessProbe: {}
resources: {}
#resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
nodeSelector: {}
tolerations: []
