repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"

docker:
  socket:
    path: "/var/run/docker.sock" # pks - /var/vcap/data/sys/run/docker/docker.sock

serviceAccount: "csp-sa"
server:
  serviceName: "csp-console-svc" # example
  port: 8080

image:
  repository: scanner
  tag: "4.6"
  pullPolicy: IfNotPresent

user:
password:
replicaCount: 1
livenessProbe: {}
readinessProbe: {}
resources: {}
#resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
 # limits:
  #  cpu: 800m
  #  memory: 6Gi
  #requests:
  #  cpu: 500m
  #  memory: 2Gi
  # For recommendations please check the official sizing guide.
nodeSelector: {}
tolerations: []
affinity: {}
